name: ci

on:
  push:
    branches:
      - "master"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tda:backend-latest
          secrets: |
            "CLOUDFLARE_TURNSTILE_SECRET_KEY=${{ secrets.CLOUDFLARE_TURNSTILE_SECRET_KEY }}"
            "FIREBASE_API_KEY=${{ secrets.FIREBASE_API_KEY }}"
            "PRIVATE_CERTIFICATE_CERT=${{ secrets.PRIVATE_CERTIFICATE_CERT }}"
            "PRIVATE_CERTIFICATE_KEY=${{ secrets.PRIVATE_CERTIFICATE_KEY }}"
            "TDA_API_KEY=${{ secrets.TDA_API_KEY }}"
            "JWT_ACCESS_TOKEN_SECRET=${{ secrets.JWT_ACCESS_TOKEN_SECRET }}"
            "JWT_REFRESH_TOKEN_SECRET=${{ secrets.JWT_REFRESH_TOKEN_SECRET }}"
            "DATABASE_URL=${{ secrets.DATABASE_URL }}"
